server:
  port: 9999

spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/orm?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

swagger:
  enabled: true
  title: xiao-demo
  description: spring boot 所有相关的最佳实践
  version: 0.0.1-SNAPSHOT
  contact:
    name: xiaobao
    email: mailbaoqiang@gmail.com
  base-package: org.xiao.springboot




